name: Trigger lib web header update

on:
  workflow_run:
    workflows: [ Validate ]
    branches: [ "main" ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Commit message
        required: true
        type: string


jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch update request
        env:
          ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACTIONS_KEY" \
            https://api.github.com/repos/PavelProjects/SmartThingLib/dispatches \
            -d '{"event_type": "ui_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'",  "message": "${{ github.event.workflow_run.head_commit.message }}" }}'