name: Update web header

on:
  push:
    branches:
      - main

env:
  COMMIT_MESSAGE: ${{ github.event.client_payload.message }}

jobs:
  update-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - run: echo $COMMIT_MESSAGE
      - name: Checkout web repository
        uses: actions/checkout@master
        with:
          repository: PavelProjects/SmartThingLibWeb
          path: ./web
      - run: pwd && cd ./web
      - run: pwd
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Update header header
        run: npm run build-header