name: Trigger lib web header update

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Commit message
        required: true
        type: string

env:
  COMMIT_MESSAGE: "${{ github.event.workflow_run.head_commit.message }}${{ inputs.commitMessage }}"
  ACTIONS_KEY: ${{ secrets.ACTIONS_KEY }}
  TEST_SECRET: ${{ secrets.TEST_SECRET }}
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
  JUST_SECRET: "not so a secret"

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Repository dispatch update request
        run: curl -X POST "https://pobopo.ru/st/test$COMMIT_MESSAGE$ACTIONS_KEY"
        # run: |
        #   curl -L \
        #     -X POST \
        #     -H "Accept: application/vnd.github+json" \
        #     -H "Authorization: Bearer $ACTIONS_KEY" \
        #     https://api.github.com/repos/PavelProjects/SmartThingLib/dispatches \
        #     -d '{"event_type": "ui_update", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'",  "message": "$COMMIT_MESSAGE" }}'