name: Update web header

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ui_update]
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Commit message
        required: true
        type: string

env:
  COMMIT_MESSAGE: "${{ github.event.client_payload.message }}${{ inputs.commitMessage }}"

jobs:
  update-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - run: echo $COMMIT_MESSAGE